#!/bin/env python
#!/home/illia/python_env/bin/python

import typer
import requests
import json
from pathlib import Path

app = typer.Typer()
BASE_URL = "http://localhost:8080"

@app.command()
def import_(file: Path):
    """Import mol file"""

    if not file.exists():
        typer.echo(f"File '{file}' not exists")
        raise typer.Exit(1)

    with file.open("rb") as f:
        files = {"file": f}
        response = requests.post(f"{BASE_URL}/import", files=files)
        typer.echo(response.text)

@app.command()
def products(names: list[str]):
    """Products search"""

    body = json.dumps(names)
    headers = {"Content-Type": "application/json"}
    response = requests.get(f"{BASE_URL}/products?asText=true", data=body, headers=headers)
    typer.echo(response.text)

@app.command()
def reagents(name: str):
    """Reagents search"""

    response = requests.get(f"{BASE_URL}/reagents?asText=true", data=name)
    typer.echo(response.text)

if __name__ == "__main__":
    app()
